#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

WRITE_INFO = "write_info"
WAIT_REVIEW = "wait_review"
WAIT_DELEGATE = "wait_delegate"
WAIT_PAYMENT = "wait_payment"
PAID = "paid"
COMPLETED = "completed"
INVALID = "invalid"
WAITE_UPLOAD = "wait_upload"
STUFF_SEND = "stuff_send"
