#starting options have parameter --runmod default is:development
# 用于合同生成的代理公司联系人的信息配置

mark:
  link_man: 焦枫婉
  phone: 18500139155
  agency: 北京易正达知识产权代理有限公司
  post_num: 100029

copyright:
  link_man: 焦枫婉
  phone: 18500139155
  agency: 北京易正达知识产权代理有限公司
  post_num: 100029