# 错误信息配置表
# 错误信息格式规范：
# 系统错误都从10000起步，10000到19999表示系统错误
# 逻辑错误都从20000起步，20000及其以上都采用这个错误提示
# 错误的书写规范，key表示错误code，value表示的文案：
# 例如：
# 20001: 此用户已注册
# 20002: 长度不能超过{1}

10005: 客服还没准备好


10050: order_operate 操作类未初始化

# account user module
20000: 该手机号已被注册
20001: 此邮箱已注册
20002: 用户名或密码错误
20003: 当前用户已被系统锁定
20004: 此账号不存在
20005: 输入次数过多，此账号已被锁定，请1小时候再尝试登录
20006: 此账号已被锁定，请1小时候再尝试登录
20007: 手机号或密码错误
20008: 请输入图像验证码
20009: 图像验证码不正确
20010: 当前登录密码不正确

# 手机验证码服务相关的错误提示
20101: 输入错误次数过多，请重新获取验证码
20102: 验证码错误，请重新输入
20103: 没有此验证码

20104: 点击太过频繁，请稍后再获取验证码
20105: 发送太过频繁，请稍后再获取验证码
20107: 发送接口报错，请联系管理员
20030: 此用户名已被占用，请更换用户名

#邮箱重置密码
20040: token不正确
20041: token已过期。请重新获取验证邮件
20042: 发送太频繁。五分钟内不允许发送多次

#融资项目 业务报错
20050: 该项目已经发布，无权修改
20051: 项目编辑出错，缺失图片序列

# 通用错误
20403: 您无权进行此操作！

# 业务流程报错
20051: 没有找到该订单
20052: 对不起，您选择的服务不存在
20053: 对不起，订单类型错误
20054: 请确保您的商品小项全部属于同一个一级大类
20055: 您的商标注册流程未完成。不能确认该订单
20056: 该订单已确认，不能在申请代填
20060: 没有找到该商标注册信息
20065: 商标所属用户与当前登录用户不符
20070: 订单已确认，不能修改订单信息
20071: 未找到相关的主体信息
20075: 该订单的业务信息与记录不符
20080: 该订单下没有此合同
20090: 该订单未关联任何主体信息，请联系客服人员
20091: 该订单未付款。无法获取合同


# 产品金额报错
20080: 对不起，您所选产品金额存在错误
20085: 该订单已支付

# 发票部分报错
20090: 您没有选择要开票的订单
20091: 该订单已经开过发票
20092: 发票金额错误，无法完成操作

