development:
  default:
    servers:
      - 192.168.0.201:11211
    behaviors:
    binary: True
    username:
    password:
    enabled: True
  captcha:
    servers:
      - 192.168.0.201:11211
    behaviors:
    binary: True
    username:
    password:
    enabled: True
  itemarea:
    servers:
      - 192.168.0.201:11211
    behaviors:
    binary: True
    username:
    password:
    enabled: True
  produce:
    servers:
      - 192.168.0.201:11211
    behaviors:
    binary: True
    username:
    password:
    enabled: True

test:
  default:
    servers: 127.0.0.1:11211
    behaviors:
    binary: True
    username:
    password:
    enabled: True
  captcha:
    servers:
      - 192.168.1.136:11211
    behaviors:
    binary: True
    username:
    password:
    enabled: True

production:
  default:
    servers: 127.0.0.1:11211
    behaviors:
    binary:
    username:
    password:
    enabled: True
  captcha:
    servers:
      - 127.0.0.1:11211
    behaviors:
    binary: True
    username:
    password:
    enabled: True
  itemarea:
    servers:
      - 127.0.0.1:11211
    behaviors:
    binary: True
    username:
    password:
    enabled: True
  produce:
    servers:
      - 127.0.0.1:11211
    behaviors:
    binary: True
    username:
    password:
    enabled: True