#starting options have parameter --runmod default is:development

alipay:
# 支付宝支付配置
  development:
    # 易清的
    pid: 2088211134903983
    key: 5aylmzzz17rm2crm6lmqtelay215uhnf
    seller_email: zhifubao@eking.mobi
    return_url: http://www.bingoip.com/pay/notify
    notice_url: http://www.bingoip.com/pay/notify

  production:
  # 易正达的
    pid: 2088021214687384
    key: wuux79bjvrzacjjieyzsmnv0to9c9082
    seller_email: qiyeyouxiang@yestar.mobi
    return_url: http://www.bingoip.com/pay/notify
    notice_url: http://www.bingoip.com/pay/notify


wxpay:
# 微信支付配置
  development:
    # 易清的
    pid: 2088211134903983


  production:
  # 易正达的
    pid: 2088021214687384

