signup: "{0}(验证码){1}客服绝不会索取此验证码，请勿将此验证码告知他人【{1}】"
reset_password: "{0}(验证码){1}客服绝不会索取此验证码，请勿将此验证码告知他人【{1}】"
account_change: 【{1}】{0}(验证码){1}客服绝不会索取此验证码，请勿将此验证码告知他人
password_changed_notice: 您的账号{0}所关联的密码在{1}被修改，如不是本人操作请及时与客服联系【{2}】

order_status_changed: "您的订单: {0} 状态更新为 {1} , 订单号:{2}，时间：{3}【{4}】"

forecast_mark_success: "您在冰狗网检索的商标：{0}，经过我们专业顾问对在先数据的检索，未发现已经申请的近似商标，请尽快到冰狗网免费申请吧。【{1}】 "

bingo_reject: "您在冰狗网提交审核的{0}：{1} 被驳回。驳回理由如下: {2}。【{3}】 "

