#starting options have parameter --runmod default is:development
development:
  default:
    host: 192.168.0.201
    port: 20880
  cs_order:
    host: 127.0.0.1
    port: 20880

test:
  default:
    host: 192.168.0.201
    port: 20880

production:
  default:
    host: 123.57.76.42
    port: 20880
  cs_order:
    port: 20880
